# create variable tensors with the corresponding methods

In [2]:
import tensorflow as tf

In [3]:
xvar=tf.random.normal(shape=(3,3))

In [4]:
xvar

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.1126947 ,  0.88340896,  0.30006835],
       [ 0.87129664,  0.17544802,  0.09124355],
       [-0.07546281,  1.0176201 ,  0.04334327]], dtype=float32)>

In [5]:
a=tf.Variable(xvar)

In [6]:
a

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 1.1126947 ,  0.88340896,  0.30006835],
       [ 0.87129664,  0.17544802,  0.09124355],
       [-0.07546281,  1.0176201 ,  0.04334327]], dtype=float32)>

In [7]:
a.assign(tf.random.normal(shape=(3,3)))

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[-0.2802384 ,  0.22264999,  0.2217753 ],
       [ 1.340495  ,  0.21808411, -0.79762644],
       [ 1.0730777 , -1.5985533 , -0.22874902]], dtype=float32)>

In [8]:
xvar_t_add=tf.random.normal(shape=(3,3))

In [9]:
xvar_t_add

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.4657497 , -1.1722509 ,  0.7237519 ],
       [ 0.287711  , -0.19811721, -0.05307561],
       [ 0.9014626 ,  0.36722845, -0.13447502]], dtype=float32)>

In [10]:
a.assign_add(xvar_t_add)

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[-1.7459881 , -0.9496009 ,  0.9455272 ],
       [ 1.628206  ,  0.0199669 , -0.85070205],
       [ 1.9745402 , -1.2313249 , -0.36322403]], dtype=float32)>

In [11]:
a.assign_sub(xvar_t_add)

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[-0.2802384 ,  0.22264999,  0.2217753 ],
       [ 1.340495  ,  0.21808411, -0.79762644],
       [ 1.0730777 , -1.5985534 , -0.228749  ]], dtype=float32)>

In [12]:
new_value=tf.random.normal(shape=(3,3))
new_value

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.36468646,  0.93324083,  0.47895434],
       [-0.51162946,  2.3992991 , -0.16825075],
       [-0.7021468 ,  0.49745294,  0.67879194]], dtype=float32)>

In [13]:
a

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-0.2802384 ,  0.22264999,  0.2217753 ],
       [ 1.340495  ,  0.21808411, -0.79762644],
       [ 1.0730777 , -1.5985534 , -0.228749  ]], dtype=float32)>

In [14]:
a.assign_add(new_value)

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[-0.6449249 ,  1.1558908 ,  0.7007296 ],
       [ 0.8288655 ,  2.6173832 , -0.9658772 ],
       [ 0.37093085, -1.1011004 ,  0.45004293]], dtype=float32)>

In [15]:
b=tf.random.normal(shape=(3,3))

In [16]:
b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.29989848,  0.37880355,  0.77906215],
       [ 0.0165449 , -1.2872458 ,  0.5284248 ],
       [-2.229802  , -0.71475446, -0.51731104]], dtype=float32)>

In [17]:
c=a+b
c

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.9448234 ,  1.5346944 ,  1.4797918 ],
       [ 0.8454104 ,  1.3301375 , -0.43745238],
       [-1.858871  , -1.8158549 , -0.0672681 ]], dtype=float32)>

In [18]:
d=tf.square(c)
d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.89269125, 2.355287  , 2.1897836 ],
       [0.71471876, 1.7692658 , 0.19136459],
       [3.4554014 , 3.297329  , 0.004525  ]], dtype=float32)>

In [19]:
e=tf.exp(c)
e

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.38874823, 4.6399074 , 4.392031  ],
       [2.3289332 , 3.7815633 , 0.6456793 ],
       [0.15584849, 0.16269876, 0.9349445 ]], dtype=float32)>

In [20]:
with tf.GradientTape() as tape:

IndentationError: expected an indented block (3986227147.py, line 1)

In [21]:
with tf.GradientTape() as tape:
    tape.watch(a)
    f=tf.sqrt(tf.square(a)+tf.square(b))
    df_da=tape.gradient(f,a)
    print(df_da)

tf.Tensor(
[[-0.90675694  0.9502726   0.66874   ]
 [ 0.9998008   0.8973489  -0.87729055]
 [ 0.16409649 -0.83877796  0.65635085]], shape=(3, 3), dtype=float32)
